import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { TABLE_NAMES } from '@/server/db/schema';
import { makeStore } from './helpers';
import { signUp } from '@/server/services/auth';
import { completeOnboarding } from '@/server/services/onboarding';
import { createProject } from '@/server/services/projects';
import { createShareLink } from '@/server/services/shares';
import { createThread } from '@/server/services/comments';
import { buildPreview } from '@/server/services/preview';

/**
 * Do the migrations accept what the code actually writes?
 *
 * The production incident was a storage driver that could not write at all. The
 * failure waiting immediately behind it is subtler and just as invisible: the
 * code gains a field, the migration does not, and Postgres rejects the insert
 * with `42703` — on the deployed site only, because the local JSON driver has no
 * schema and happily stores anything.
 *
 * So this suite does not compare types to SQL by eye. It runs the real services
 * against a real store, takes the rows they genuinely produce, and checks every
 * key against the real column list — captured by applying
 * `supabase/migrations/*.sql` to a real Postgres 16 and introspecting it
 * (`tests/fixtures/postgres-schema.json`, regenerated by
 * `node scripts/snapshot-schema.mjs`).
 *
 * If this fails, production is about to reject an insert. Add the migration.
 */

interface SchemaSnapshot {
  tables: Record<string, string[]>;
}

const snapshot = JSON.parse(
  readFileSync(path.join(process.cwd(), 'tests/fixtures/postgres-schema.json'), 'utf8'),
) as SchemaSnapshot;

/** The driver's camelCase → snake_case conversion, which must match exactly. */
function camelToSnake(value: string): string {
  return value.replace(/[A-Z]/g, (character) => `_${character.toLowerCase()}`);
}

describe('the migrations cover every table the code knows about', () => {
  it('has a table for every entry in TABLE_NAMES', () => {
    const missing = TABLE_NAMES.map(camelToSnake).filter((table) => !snapshot.tables[table]);
    expect(missing).toEqual([]);
  });

  it('has no table the code does not know about', () => {
    const known = new Set(TABLE_NAMES.map(camelToSnake));
    const orphans = Object.keys(snapshot.tables).filter((table) => !known.has(table));
    expect(orphans).toEqual([]);
  });
});

describe('the migrations accept the rows the services actually write', () => {
  /**
   * Exercises the whole write surface once, then asserts every column it touched
   * exists. Doing it through the services rather than hand-written fixtures is
   * the point: a field added to a row shape is caught even if nobody remembers
   * to update a test.
   */
  it('accepts everything a full sign-up → onboarding → share journey writes', async () => {
    const { store, cleanup } = await makeStore();
    try {
      const { user } = await signUp(
        store,
        { name: 'Léa Martin', email: 'lea@example.com', password: 'a-good-password' },
        'vitest',
      );
      const actor = { userId: user.id, via: 'session' as const };

      const completed = await completeOnboarding(store, actor, {
        draft: {
          appName: 'Padel Nord',
          category: 'booking',
          summary: 'Members book a court.',
          roles: ['member', 'club'],
          startWith: 'generated',
        },
      });
      const projectId = completed.project!.id;

      // Touch the remaining write paths so their tables are covered too.
      await buildPreview(store, projectId, 'working', 'system');
      const device = (await store.select('devices', { match: { projectId } }))[0]!;
      const share = await createShareLink(store, projectId, actor.userId, {
        label: 'Schema test',
        versionId: null,
        access: 'comment',
        visibility: 'public',
        allowedEmails: [],
        allowedRoles: [],
        allowVersionCompare: true,
        allowJourneys: true,
        expiresInDays: 7,
      });
      await createThread(store, projectId, share.id, 'guest', {
        deviceId: device.id,
        versionId: null,
        role: device.role,
        screen: '/',
        anchorX: 0.5,
        anchorY: 0.5,
        sourceRef: 'src/App.tsx:12:3',
        elementLabel: 'Book',
        body: 'Written by the schema test.',
        authorName: 'A reviewer',
      });
      await createProject(store, actor, {
        workspaceId: user.activeWorkspaceId!,
        name: 'Second project',
        templateId: 'starter',
      });

      /* Every row the journey produced, checked against the real columns. */
      const problems: string[] = [];
      let checkedTables = 0;
      let checkedColumns = 0;

      for (const table of TABLE_NAMES) {
        const rows = await store.select(table, {});
        if (rows.length === 0) continue;
        checkedTables += 1;

        const sqlTable = camelToSnake(table);
        const columns = new Set(snapshot.tables[sqlTable] ?? []);

        // Union of keys across rows: optional fields may be absent on some.
        const keys = new Set<string>();
        for (const row of rows) for (const key of Object.keys(row)) keys.add(key);

        for (const key of keys) {
          checkedColumns += 1;
          const column = camelToSnake(key);
          if (!columns.has(column)) {
            problems.push(
              `${sqlTable}.${column} — written by the code as "${key}", absent from the migrations`,
            );
          }
        }
      }

      expect(problems).toEqual([]);
      // A guard against the assertion above passing because nothing was checked.
      expect(checkedTables).toBeGreaterThanOrEqual(10);
      expect(checkedColumns).toBeGreaterThanOrEqual(80);
    } finally {
      await cleanup();
    }
  });

  it('covers the onboarding columns that 0002 added', () => {
    const users = snapshot.tables.users ?? [];
    for (const column of [
      'onboarding_completed_at',
      'onboarding_step',
      'onboarding_draft',
      'active_workspace_id',
      'active_project_id',
      'preferences',
    ]) {
      expect(users, `users.${column} is missing — 0002_onboarding.sql not applied`).toContain(
        column,
      );
    }

    const projects = snapshot.tables.projects ?? [];
    expect(projects).toContain('is_demo');
    expect(projects).toContain('brief');
  });
});
